install.packages('keras')
library(keras)
install_keras()
install.packages("BiocManager")
BiocManager::install("ChemmineR")
BiocManager::install("ChemmineOB")
devtools::install_github("TomasVrzal/DeepReI")