install.packages('keras')
library(keras)
install_keras()
install.packages("BiocManager")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ChemmineR")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ChemmineOB")
devtools::install_github("TomasVrzal/DeepReI/main/")